@hostname = http://localhost:9000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoemFiYWtoIiwiaWQiOjIsImlhdCI6MTY3NzE3NjM2MX0.UPB8wrZcstX3qUMHNDgTcvnyffZjC4KRa0_qByuKnqI

### ------------------------------- REGISTER -------------------------------
POST {{hostname}}/auth/register
Content-Type: application/json

{
    "email": "saad.ayar@hotmail.com",
    "password": "Q@qweqwe123",
    "firstname": "Saad",
    "lastname": "Ayar",
    "nickname": "DayneeBoiiz"
}

# return {{token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoemFiYWtoIiwiaWQiOjIsImlhdCI6MTY3NzE3NjM2MX0.UPB8wrZcstX3qUMHNDgTcvnyffZjC4KRa0_qByuKnqI}}
# username: between 2 & 35 characters, and can be alphanumeric
# password: between 6 and 20 characters
# -------------------------------------------------------------------------

### ------------------------------- LOGIN ---------------------------------
POST {{hostname}}/auth/login
Content-Type: application/json

{
    "email":"saad.ayar@hotmail.co",
	"password":"Q@qweqwe123"
}

# return {{token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoemFiYWtoIiwiaWQiOjIsImlhdCI6MTY3NzE3NjM2MX0.UPB8wrZcstX3qUMHNDgTcvnyffZjC4KRa0_qByuKnqI}}
#--------------------------------------------------------------------------

### ------------------------------- GENERATE 2FA --------------------------
POST {{hostname}/2fa/generate}
Authorization: {{token}}

#--------------------------------------------------------------------------

### ------------------------------- VERIFY 2FA ----------------------------
POST {{hostname}/2fa/verify}
Authorization: {{token}}
Content-Type: application/json

{
    "code": "369083"
}

# return {{true/false}}
#--------------------------------------------------------------------------

### ------------------------------- CHANGE 2FA ----------------------------
POST {{hostname}/2fa/change}
Authorization: {{token}}

#--------------------------------------------------------------------------

### ------------------------------- STATUS 2FA ----------------------------
GET {{hostname}/2fa/status}
Authorization: {{token}}

# return {{true/false}}
#--------------------------------------------------------------------------

### ------------------------------- CREATE ROOM ---------------------------
POST {{hostname}/chat/createroom}
Authorization: {{token}}
Content-Type: application/json

{
    "roomName": "DayneeBoiiz"
}
#--------------------------------------------------------------------------

### ------------------------------- SET ADMIN -----------------------------
POST {{hostname}/chat/setadmin}
Authorization: {{token}}
Content-Type: application/json

{
    "roomId": 1,
    "userId": 2
}
#--------------------------------------------------------------------------

### ------------------------------- 42 LOGIN ------------------------------
GET {{hostname}/auth/42/login}
#--------------------------------------------------------------------------

### ------------------------------- GET ALL USERS -------------------------
GET {{hostname}/users/all-users}
Authorization: {{token}}

return : 
[
    {
        "id": 1,
        "createdAt": "2023-07-17T11:30:41.413Z",
        "updatedAt": "2023-07-17T11:50:59.441Z",
        "email": "saad.ayar@hotmail.com",
        "nickname": "DayneeBoiiz",
        "firstname": "Saad",
        "lastname": "Ayar",
        "TwofaAutEnabled": true,
        "avatarUrl": null
    },
    {
        "id": 2,
        "createdAt": "2023-07-17T11:59:48.390Z",
        "updatedAt": "2023-07-17T11:59:48.390Z",
        "email": "saad.ayar@hotmail.co",
        "nickname": "FixGree",
        "firstname": "Saad",
        "lastname": "Ayar",
        "TwofaAutEnabled": false,
        "avatarUrl": null
    },
    {
        "id": 3,
        "createdAt": "2023-07-17T12:35:25.323Z",
        "updatedAt": "2023-07-17T12:35:25.323Z",
        "email": "sayar@student.1337.ma",
        "nickname": "sayar",
        "firstname": "Saad",
        "lastname": "Ayar",
        "TwofaAutEnabled": false,
        "avatarUrl": null
    }
]
#--------------------------------------------------------------------------

### ------------------------------- SEND FRIEND REQUEST -------------------
POST {{hostname/users/{username}/send-friend-request}}
Authorization: {{token}}
Content-Type: application/json
Params: {username}

{
    "recipientUserName": "FixGree"
}
#--------------------------------------------------------------------------

### ------------------------------- ACCEPT FRIEND REQUEST -----------------
POST {{hostname}/{senderusername}/friend-request/{receiverusername}/accept}
Authorization: {{token}}
#--------------------------------------------------------------------------

### ------------------------------- REMOVE FRIEND REQUEST -----------------
DELETE {{hostname}/users/{username}}
Authorization: {{token}}
Param: {username}
#--------------------------------------------------------------------------

### ------------------------------- REJECT FRIEND REQUEST -----------------
POST {{hostname}/users/{username}/reject}
Authorization: {{token}}
Param: {username}
#--------------------------------------------------------------------------