version: '3'

services:
  postgres:
    container_name: backendCollab
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=dev_db
    networks:
      - dev_network

networks:
  dev_network: